final Map<String, String> citiesMap = {
  "Hà Nội":"Ha Noi",
  "Hải Phòng":"Hai Phong",
  "Đà Nẵng":"Da Nang",
  "Hồ Chí Minh":"Ho Chi Minh",
  "Cần Thơ":"Can Thơ",
  "Thủ Đức":"Thu Duc",
  "Long Xuyên":"Long Xuyen",
  "Vũng Tàu":"Vung Tau",
  "Bắc Giang":"Bac Giang",
  "Bắc Ninh":"Bac Ninh",
  "Quy Nhơn":"Quy Nhon",
  "Thủ Dầu Một":"Thu Dau Mot",
  "Đồng Xoài":"Dong Xoai",
  "Phan Thiết":"Phan Thiet",
  "La Gi":"La gi",
  "Cà Mau":"Ca Mau",
  "Buôn Ma Thuột":"Buon Ma Thuot",
  "Điện Biên":"Dien Bien",
  "Biên Hòa":"Bien Hoa",
  "Cao Lãnh":"Cao Lanh",
  "Pleiku":"Pleiku",
  "Hà Giang":"Ha Giang",
  "Phủ Lý":"Phu Ly",
  "Hải Dương":"Hai Duong",
  "Hòa Bình":"Hoa Binh",
  "Hưng Yên":"Hung Yen",
  "Nha Trang":"Nha Trang",
  "Cam Ranh":"Cam Ranh",
  "Rạch Giá":"Rach Gia",
  "Lai Châu":"Lai Chau",
  "Lào Cai":"Lao Cai",
  "Đà Lạt":"Da Lat",
  "Phan Rang-Tháp Chàm":"Phan Rang- Thap Cham",
  "Việt Trì":"Viet Tri",
  "Tam Kỳ":"Tam Ky",
  "Hội An":"Hoi An",
  "Bạc Liêu":"Bac Lieu",
  "Sóc Trăng":"Soc Trang",
  "Bến Tre":"Ben Tre",
  "Trà Vinh":"Tra Vinh",
  "Vĩnh Long":"Vinh Long",
  "Tiền Giang":"Tien Giang",
  "Long An":"Long An",
  "Bình Dương":"Binh Duong",
  "Đồng Nai":"Dong Nai",
  "Bình Thuận":"Binh Thuan",
  "Khánh Hòa":"Khanh Hoa",
  "Lâm Đồng":"Lam Dong",
  "Bình Định":"Binh Dinh",
  "Phú Yên":"Phu Yen",
  "Quảng Nam":"Quang Nam",
  "Quảng Ngãi":"Quang Ngai",
  "Quảng Trị":"Quang Tri",
  "Thừa Thiên - Huế":"Thua Thien - Hue",
  "Quảng Bình":"Quang Binh",
  "Hà Tĩnh":"Ha Tinh",
  "Nghệ An":"Nghe An",
  "Yên Bái":"Yen Bai",
  "Phú Thọ":"Phu Tho",
  "Vĩnh Phúc":"Vinh Phuc",
  "Thái Nguyên":"Thai Nguyen",
  "Lạng Sơn":"Lang Son",
  "Bắc Kạn":"Bac Kan",
  "Cao Bằng":"Cao Bang",
  "Thái Bình":"Thai Binh",
  "Hà Nam":"Ha Nam",
  "Ninh Bình":"Ninh Binh",
  "Thanh Hóa":"Thanh Hoa",
  "Kon Tum":"Kon Tum",
  "Gia Lai":"Gia Lai",
  "Đắk Lắk":"Dac Lac",
  "Ninh Thuận":"Ninh Thuan",
  "An Giang":"An Giang",
  "Kiên Giang":"Kien Giang",
  "Tây Ninh":"Tay Ninh",
  "Đồng Tháp":"Dong Thap",
  "Tuyên Quang":"Tuyen Quang",
  "Vinh":"Vinh",
  "Uông Bí":"Uong Bi",
  "Tuy Hòa":"Tuy Hoa",
  "Sơn La":"Sơn La",
  "Sa Pa":"Sa Pa",
  "Quảng Ninh":"Quang Ninh",
  "Mỹ Tho":"My Tho",
  "Hà Tây":"Ha Tay",
  "Củ Chi":"Cu Chi",
  "Châu Đốc":"Chau Doc",
  "Cần Giờ":"Can Gio",
  "Hậu giang": "Hau Giang",
  "Bình Phước": "Binh Phuoc",
  "Tân An": "Tan An",
  "Tam Điệp": "Tam Diep",
  "Nam Định": "Nam Dinh",
  "Móng Cái": "Mong Cai",
  "Hạ Long": "Ha Long",
  "Đông Hà": "Dong Ha",
  "Cẩm Phả": "Cam Pha",
};