
// Danh sách các thành phố
final List<String> citiesList = [
  "Hà Nội",
  "Hải Phòng",
  "Đà Nẵng",
  "Hồ Chí Minh",
  "Cần Thơ",
  "Thủ Đức",
  "Long Xuyên",
  "Vũng Tàu",
  "Bắc Giang",
  "Bắc Ninh",
  "Quy Nhơn",
  "Thủ Dầu Một",
  "Đồng Xoài",
  "Phan Thiết",
  "La Gi",
  "Cà Mau",
  "Buôn Ma Thuột",
  "Điện Biên",
  "Biên Hòa",
  "Cao Lãnh",
  "Pleiku",
  "Hà Giang",
  "Phủ Lý",
  "Hải Dương",
  "Hòa Bình",
  "Hưng Yên",
  "Nha Trang",
  "Cam Ranh",
  "Rạch Giá",
  "Lai Châu",
  "Lào Cai",
  "Đà Lạt",
  "Phan Rang-Tháp Chàm",
  "Việt Trì",
  "Tam Kỳ",
  "Hội An",
  "Bạc Liêu",
  "Sóc Trăng",
  "Bến Tre",
  "Trà Vinh",
  "Vĩnh Long",
  "Tiền Giang",
  "Long An",
  "Bình Dương",
  "Đồng Nai",
  "Bình Thuận",
  "Khánh Hòa",
  "Lâm Đồng",
  "Bình Định",
  "Phú Yên",
  "Quảng Nam",
  "Quảng Ngãi",
  "Quảng Trị",
  "Thừa Thiên - Huế",
  "Quảng Bình",
  "Hà Tĩnh",
  "Nghệ An",
  "Yên Bái",
  "Phú Thọ",
  "Vĩnh Phúc",
  "Thái Nguyên",
  "Lạng Sơn",
  "Bắc Kạn",
  "Cao Bằng",
  "Thái Bình",
  "Hà Nam",
  "Ninh Bình",
  "Thanh Hóa",
  "Kon Tum",
  "Gia Lai",
  "Đắk Lắk",
  "Ninh Thuận",
  "An Giang",
  "Kiên Giang",
  "Tây Ninh",
  "Đồng Tháp",
  "Tuyên Quang",
  "Vinh",
  "Uông Bí",
  "Tuy Hòa",
  "Sơn La",
  "Sa Pa",
  "Quảng Ninh",
  "Mỹ Tho",
  "Hà Tây",
  "Củ Chi",
  "Châu Đốc",
  "Cần Giờ",
  'Hậu giang',
  'Bình Phước',
  'Tân An',
  'Tam Điệp',
  'Nam Định',
  'Móng Cái',
  'Hạ Long',
  'Đông Hà',
  'Cẩm Phả',

];
